steps:
  # === build image ===
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/brothergev-mvp-477006/ev-ai-final:latest", "."]

  # === push image ===
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/brothergev-mvp-477006/ev-ai-final:latest"]

  # === deploy ===
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "run", "deploy", "ev-ai-final",
        "--region=europe-west4",
        "--image=gcr.io/brothergev-mvp-477006/ev-ai-final:latest",
        "--set-secrets=OPENAI_API_KEY=openai-api-key:latest"
      ]

timeout: "900s"
