steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ev-api-english-gpt:$SHORT_SHA', '.']

  - name: 'gcr.io/google-cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ev-api-english-gpt'
      - '--region=europe-west4'
      - '--image=gcr.io/$PROJECT_ID/ev-api-english-gpt:$SHORT_SHA'
      - '--allow-unauthenticated'
      - '--service-account=234402937661-compute@developer.gserviceaccount.com'
      - '--set-secrets=OPENAI_API_KEY=openai-api-key:latest'
      - '--update-env-vars=OPENAI_MODEL=gpt-4o-mini'

images:
  - 'gcr.io/$PROJECT_ID/ev-api-english-gpt:$SHORT_SHA'
